/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for MediaLibraryController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_MYHOMEAPICLIENT, CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { PageRequest, RequestOptions, PageResultTvShow, NewTvShowRequest, TvShow, PageResultFilm, NewFilmRequest, Film } from "../models";

@Injectable({ providedIn: "root" })
export class MediaLibraryControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_MYHOMEAPICLIENT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'MyHomeApiClient');
    }

    listTvShows(pageRequest: PageRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<PageResultTvShow>;
    listTvShows(pageRequest: PageRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PageResultTvShow>>;
    listTvShows(pageRequest: PageRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PageResultTvShow>>;
    listTvShows(pageRequest: PageRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/media/tvShows`;

        let params = new HttpParams();
        if (pageRequest != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageRequest, 'pageRequest');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createNewTvShow(newTvShowRequest: NewTvShowRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<TvShow>;
    createNewTvShow(newTvShowRequest: NewTvShowRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TvShow>>;
    createNewTvShow(newTvShowRequest: NewTvShowRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TvShow>>;
    createNewTvShow(newTvShowRequest: NewTvShowRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/media/tvShows`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, newTvShowRequest, requestOptions);
    }

    listFilms(pageRequest: PageRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<PageResultFilm>;
    listFilms(pageRequest: PageRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PageResultFilm>>;
    listFilms(pageRequest: PageRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PageResultFilm>>;
    listFilms(pageRequest: PageRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/media/films`;

        let params = new HttpParams();
        if (pageRequest != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageRequest, 'pageRequest');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createNewFilm(newFilmRequest: NewFilmRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<Film>;
    createNewFilm(newFilmRequest: NewFilmRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Film>>;
    createNewFilm(newFilmRequest: NewFilmRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Film>>;
    createNewFilm(newFilmRequest: NewFilmRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/media/films`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, newFilmRequest, requestOptions);
    }
}
