/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for SearchController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_MYHOMEAPICLIENT, CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { AcceptDownloadRequest, RequestOptions, DownloadQueueItem, SearchResult, TvShow, Film } from "../models";

@Injectable({ providedIn: "root" })
export class SearchControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_MYHOMEAPICLIENT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'MyHomeApiClient');
    }

    acceptNewSearchResult(acceptDownloadRequest: AcceptDownloadRequest, observe?: 'body', options?: RequestOptions<'blob'>): Observable<DownloadQueueItem>;
    acceptNewSearchResult(acceptDownloadRequest: AcceptDownloadRequest, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<DownloadQueueItem>>;
    acceptNewSearchResult(acceptDownloadRequest: AcceptDownloadRequest, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<DownloadQueueItem>>;
    acceptNewSearchResult(acceptDownloadRequest: AcceptDownloadRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/search/accept`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, acceptDownloadRequest, requestOptions);
    }

    search(q: string, observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<SearchResult>>;
    search(q: string, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<SearchResult>>>;
    search(q: string, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<SearchResult>>>;
    search(q: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/search`;

        let params = new HttpParams();
        if (q != null) {
            params = HttpParamsBuilder.addToHttpParams(params, q, 'q');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    findAllTvShows(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<TvShow>>;
    findAllTvShows(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<TvShow>>>;
    findAllTvShows(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<TvShow>>>;
    findAllTvShows(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/search/tvShows`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    findAllFilms(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<Film>>;
    findAllFilms(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<Film>>>;
    findAllFilms(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<Film>>>;
    findAllFilms(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/search/films`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
