/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for WatchlistItemController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_MYHOMEAPICLIENT, CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { PageRequest, RequestOptions, PageResultWatchlistItem } from "../models";

@Injectable({ providedIn: "root" })
export class WatchlistItemControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_MYHOMEAPICLIENT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_MYHOMEAPICLIENT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'MyHomeApiClient');
    }

    listWatchlistItems(pageRequest: PageRequest, observe?: 'body', options?: RequestOptions<'blob'>): Observable<PageResultWatchlistItem>;
    listWatchlistItems(pageRequest: PageRequest, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<PageResultWatchlistItem>>;
    listWatchlistItems(pageRequest: PageRequest, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<PageResultWatchlistItem>>;
    listWatchlistItems(pageRequest: PageRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/v1/api/watchlist/items`;

        let params = new HttpParams();
        if (pageRequest != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageRequest, 'pageRequest');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
