/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AcceptDownloadRequest {
    searchResult?: SearchResult;
    searchResultType?: 'FILM' | 'TV_SHOW' | 'TV_SHOW_EPISODE' | 'TV_SHOW_SEASON';
    title?: string;
    year?: number;
    season?: number;
    episode?: number;
}

export interface SearchResult {
    choice?: string;
    filename?: string;
    seeds?: number;
    size?: number;
}

export interface DownloadQueueItem {
    id?: number;
    contentType?: 'TV_SHOW' | 'FILM';
    searchResultType?: 'FILM' | 'TV_SHOW' | 'TV_SHOW_EPISODE' | 'TV_SHOW_SEASON';
    hash?: string;
    filename?: string;
    percentage?: number;
    filmOrTvShowId?: number;
    season?: number;
    episode?: number;
    mbSpeed?: number;
    leachers?: number;
    seeders?: number;
    completed?: boolean;
}

export interface NewTvShowRequest {
    title?: string;
    year?: number;
}

export interface TvShow {
    id?: number;
    title?: string;
    year?: number;
    folderPath?: string;
    seasons?: Array<TvShowSeason>;
}

export interface TvShowEpisode {
    number?: number;
}

export interface TvShowSeason {
    number?: number;
    episodes?: Array<TvShowEpisode>;
}

export interface NewFilmRequest {
    title?: string;
    year?: number;
}

export interface Film {
    id?: number;
    title?: string;
    year?: number;
    folderPath?: string;
    watched?: boolean;
}

export interface PageRequest {
    page?: number;
    total?: number;
}

export interface PageResultTvShow {
    totalPages?: number;
    totalElements?: number;
    pageNumber?: number;
    pageSize?: number;
    content?: Array<TvShow>;
}

export interface PageResultFilm {
    totalPages?: number;
    totalElements?: number;
    pageNumber?: number;
    pageSize?: number;
    content?: Array<Film>;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
