/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface PageRequest {
    page?: number;
    total?: number;
}

export interface PageResultWatchlistItem {
    totalPages?: number;
    totalElements?: number;
    pageNumber?: number;
    pageSize?: number;
    content?: Array<WatchlistItem>;
}

export interface WatchlistItem {
    id?: number;
    title?: string;
    category?: 'FILM' | 'TV_SHOW';
    year?: number;
    seasons?: number;
    episodesPerSeason?: Array<number>;
    folderPath?: string;
    nodes?: Array<WatchlistItemNode>;
}

export interface WatchlistItemNode {
    title?: string;
    season?: number;
    episode?: number;
    watched?: boolean;
    downloadStatus?: 'ADDED' | 'DOWNLOADING' | 'DOWNLOADED' | 'COMPLETED' | 'ERROR';
    downloadProgress?: number;
    filePath?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
